# plugins {{{1

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
    if dein#util#_is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \   'colorscheme': 'wombat',
    \ }
'''

[[plugins]]
repo = 'tpope/vim-speeddating'

[[plugins]]
repo = 'dbeniamine/todo.txt-vim'

# colors {{{1

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
#hook_add = '''
#    set background=dark
#    au MyAutoCmd VimEnter * nested colorscheme tender
#'''

[[plugins]]
repo = 'altercation/vim-colors-solarized'
#hook_add = '''
#    let g:solarized_termcolors=256
#    set background=dark
#    au MyAutoCmd VimEnter * nested colorscheme solarized
#'''

# languages {{{1

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# end of file {{{1
# vim:ft=toml:et:nowrap:fdm=marker
